import { Column, CreateDateColumn, Entity, Index, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

export enum PurchaseOrderStatus {
  DRAFT = 'DRAFT',
  APPROVED = 'APPROVED',
  SENT = 'SENT',
  RECEIVED = 'RECEIVED',
  CANCELLED = 'CANCELLED',
}

@Entity('purchase_orders')
export class PurchaseOrder {
  @PrimaryGeneratedColumn() id: number;

  @Index({ unique: true })
  @Column({ type: 'varchar', length: 40 })
  reference: string;

  @Index()
  @Column({ name: 'supplier_id', type: 'int' })
  supplier_id: number;

  @Column({ name: 'warehouse_id', type: 'int', nullable: true })
  warehouse_id: number | null;

  // [{ productId, sku, title, quantity, unitCost, lineTotal }]
  @Column({ type: 'simple-json' })
  items: Array<{ productId: number; sku?: string; title: string; quantity: number; unitCost: number; lineTotal: number }>;

  @Column({ type: 'decimal', precision: 12, scale: 3 })
  subtotal: number;

  @Column({ type: 'decimal', precision: 12, scale: 3, default: 0 })
  tax_amount: number;

  @Column({ type: 'decimal', precision: 12, scale: 3 })
  total: number;

  @Index()
  @Column({ type: 'varchar', length: 20, default: PurchaseOrderStatus.DRAFT })
  status: PurchaseOrderStatus;

  // AUTO = generated by the forecaster, MANUAL = admin created
  @Column({ name: 'origin', type: 'varchar', length: 10, default: 'AUTO' })
  origin: 'AUTO' | 'MANUAL';

  @Column({ name: 'notes', type: 'nvarchar', length: 800, nullable: true })
  notes: string | null;

  @Column({ name: 'expected_delivery', type: 'datetime', nullable: true })
  expected_delivery: Date | null;

  @Column({ name: 'sent_at', type: 'datetime', nullable: true })
  sent_at: Date | null;

  @Column({ name: 'received_at', type: 'datetime', nullable: true })
  received_at: Date | null;

  @Column({ name: 'created_by', type: 'int', nullable: true })
  created_by: number | null;

  @CreateDateColumn({ name: 'created_at' })
  created_at: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updated_at: Date;
}
